feat: add cz config
biotope/biotope-quality-gate pull request #228
Opened 2020-08-27 11:41 UTC by no-creative-name

2020-08-27 13:46 UTC, tiagomapmarques commented on package.json
> +    "cz-customizable": "^6.3.0",
nit: `~`

2020-08-27 13:46 UTC, tiagomapmarques commented on .cz-config.js
> +};
nit: new line

2020-08-27 17:33 UTC, timomayer approved these changes

2020-08-27 17:34 UTC, timomayer commented
@tiagomapmarques i did the fixes

2020-08-27 17:36 UTC, timomayer requested changes
@no-creative-name please also add to the readme.md that the .cz-config.js in the main project has to be added and should extend this condig like for the other files already described in the readme

2020-08-27 17:42 UTC, timomayer commented
@no-creative-name oh and it is in the wrong folder should be in the config folder also like the other configs

2020-12-15 17:20 UTC, timomayer commented
@no-creative-name  will you update?

2026-07-20 13:52 UTC, closed without merging